### ISSUE TITLE
nginx config

### ISSUE THREAD

**Issue by neilstuartcraig** [http-tests/cache-tests#49]
Hi all

I'm developing a potential new test to add to the vary suite which is mainly targeted at nginx but am struggling to make it work properly. I'm wondering what nginx config you use, is that available for me to test with please?

Cheers

**Comment by neilstuartcraig** [comment]
Hello again, sorry to nag but just wondering if there's any thoughts on this yet?
I have a branch with another set of tests ready to PR but can't make it work, though i am sure the logic is sound.

**Comment by mnot** [comment]
So sorry, I completely missed this, as I forgot to watch the repo. Urgh!

The Nginx config is listed here:
  https://github.com/http-tests/cache-tests/wiki/nginx

Happy to answer any questions (hopefully more promptly!)
