### ISSUE TITLE
Header storage checks

### ISSUE THREAD

**Issue by mnot** [http-tests/cache-tests#51]
@jyasskin looking at the [storage checks](https://cache-tests.fyi/#headers), it looks like there isn't any variation between `ETag` and `Last-Modified` handling, and arguably that's not what we're interested in here (although it is covered in the update304 checks); we just want to see if particular headers are stored, so it seems to me that doing simple check on a fresh response should be adequate.

What do you think? It would cut down the number of tests in that section by about half, which would help read the results :)

Also, I'm going to take a look at the final tests and see why there are so many setup failures.

**Comment by jyasskin** [comment]
I think I only included both ETag and Last-Modified because that's what the other tests were doing. I have no objection to removing one of them.
