### ISSUE TITLE
Test for the immutable attribute

### ISSUE THREAD

**Issue by xtuc** [http-tests/cache-tests#70]
We are considering sending `Cache-Control: immutable...`  for files on cdnjs.com (https://github.com/cdnjs/cdnjs/issues/8655). However, the browser support is not ideal and it's hard to understand what's going to happen.

It would be very helpful to us to test the `immutable` attribute as part of the cache tests and I would be happy to invest the time. What do you think?

**Comment by mnot** [comment]
That would be great!

The tricky thing is to put the browsers into a state where they're reloading, to trigger the semantics of `immutable`. I think that could be achieved by using a cache mode of `no-cache` on the Fetch call, but it'd be important to verify that it has the desired effect on each browser by manually observing what's happening on the wire.

Happy to help / review / etc. as you like.

**Comment by ericlaw1979** [comment]
I have some tests and discussion at https://bayden.com/test/cache/refresh.aspx. One challenge is that there are so many different sorts of "reload" in different browsers. I think moving to `fetch` has improved the situation somewhat, but browsers are not all in perfect alignment.

**Comment by mnot** [comment]
Hm. A quick test shows that none of the major 3 browser engines seems to honour `immutable` from fetch with a cache mode of `no-cache`. 

My reading of the [fetch spec's definition of those semantics](https://fetch.spec.whatwg.org/#requests) (scroll down) is that they arguably should, or at least that it would make sense to; i.e., that `no-cache` is effectively a reload (although one might say it's a 'forced' reload; that depends on whether you take `no-cache` to be a indication from the client that a reload is necessary, but I'd say the major use case for that is corrupted or incomplete data, in which case `reload` would be the right directive).

@annevk and @mcmanus, comments?

**Comment by annevk** [comment]
See discussion in https://github.com/whatwg/fetch/issues/308.

**Comment by annevk** [comment]
(I would love it if we could get to a point where new "protocol" features have some kind of end-to-end integration performed so that everyone is aligned on what should happen everywhere in the pipeline before we declare it ready. That might help reduce the amount of time we spent on fixing things many years into the future.)

**Comment by ericlaw1979** [comment]
> none of the major 3 browser engines seems to honour 
> immutable from fetch with a cache mode of no-cache.

Do they all behave the same way in terms of request headers? E.g. do the requests send the same `Cache-Control` request header, and do they send an `If-None-Match` for the previously-cached resource?

**Comment by mnot** [comment]
Looks like they are (`max-age=0`, as Fetch requires). However, note #722.

**Comment by mnot** [comment]
AFAICT we're testing this, it's just that the browsers aren't following the spec. Please add new information if you find it; closing for now.
