### ISSUE TITLE
README vs. code - "test-cdn.html" does not exist

### ISSUE THREAD

**Issue by elithrar** [http-tests/cache-tests#71]
```
./README.md
79:To test an reverse proxy or CDN, configure it to use the server as the
origin and point a browser to `https://{hostname}/test-cdn.html`.
```

This file does not exist in the repo / is not referenced in `server.js` (i.e. generated dynamically).

**Comment by mnot** [comment]
That's leftover text; will fix. The correct instructions are just below; see also `test-host.sh`.

Thanks.
